educacion/urls.py
from django.conf.urls import url
from django.contrib import admin
from proyecto.views import login
from proyecto.views import registro
from proyecto.views import esti_form
from proyecto.views import *
from proyecto.views import configuracion
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login',login, name='login'),
    url(r'^registro',registro, name='registro'),
    url(r'^$',inicio, name='inicio'),
    #url('^hh',hh, name='hh'),
    url(r'^login',login, name='login'),
    url(r'^logout',logout, name='logout'),
    url(r'^docentes',docentes, name='docentes'),
    url(r'^veredas',veredas, name='veredas'),
    url(r'^matriculas',matriculas, name='matriculas'),
    url(r'^configuraMatricula',configuraMatricula, name='configuraMatricula'),
    url(r'^configuraInstitucion',configuraInstitucion, name='configuraInstitucion'),
    url(r'^configuraGrado',configuraGrado, name='configuraGrado'),
    url(r'^configuraSede',configuraSede, name='configuraSede'),
    url(r'^configuraGrupo',configuraGrupo, name='configuraGrupo'),
    url(r'^actualiza_alumnos',actualiza_alumnos, name='actualiza_alumnos'),
    url(r'^busquedas_alumnos',busquedas_alumnos, name='busquedas_alumnos'),
    url(r'^universidades',universidades, name='universidades'),
    url(r'^video',video, name='video'),
    url(r'^portada',portada, name='portada'),
    url(r'^busqueda_docente',busqueda_docente, name='busqueda_docente'),
    url(r'^busquedas',busquedas, name='busquedas'),
    url(r'^busquedasIncentivos',busquedasIncentivos, name='busquedasIncentivos'),
    url(r'^configuracion',configuracion, name='configuracion'),
    url(r'^busquedas2',busquedas2, name='busquedas2'),
    url(r'^municipios',municipios, name='municipios'),
    url(r'^editarBusqueda/(?P<pk>\d+)/',editarBusqueda, name='editarBusqueda'),
    url(r'^editarInstitucion/(?P<pk>\d+)/',editarInstitucion, name='editarInstitucion'),
    url(r'^editarGrado/(?P<pk>\d+)/',editarGrado, name='editarGrado'),
    url(r'^editarSede/(?P<pk>\d+)/',editarSede, name='editarSede'),
    url(r'^editarGrupo/(?P<pk>\d+)/',editarGrupo, name='editarGrupo'),
    url(r'^eliminarInstitucion/(?P<pk>\d+)/',eliminarInstitucion, name='eliminarInstitucion'),
    url(r'^eliminarSede/(?P<pk>\d+)/',eliminarSede, name='eliminarSede'),
    url(r'^eliminarGrupo/(?P<pk>\d+)/',eliminarGrupo, name='eliminarGrupo'),
    url(r'^eliminarGrado/(?P<pk>\d+)/',eliminarGrado, name='eliminarGrado'),
    url(r'^editarMunicipio/(?P<pk>\d+)/',editarMunicipio, name='editarMunicipio'),
    url(r'^eliminarMunicipio/(?P<pk>\d+)/',eliminarMunicipio, name='eliminarMunicipio'),
    url(r'^editarVereda/(?P<pk>\d+)/',editarVereda, name='editarVereda'),
    url(r'^eliminarVereda/(?P<pk>\d+)/',eliminarVereda, name='eliminarVereda'),
    url(r'^editarUniversidad/(?P<pk>\d+)/',editarUniversidad, name='editarUniversidad'),
    url(r'^eliminarUniversidad/(?P<pk>\d+)/',eliminarUniversidad, name='eliminarUniversidad'),
    url(r'^editarColegio/(?P<pk>\d+)/',editarColegio, name='editarColegio'),
    url(r'^eliminarColegio/(?P<pk>\d+)/',eliminarColegio, name='eliminarColegio'),
    url(r'^editarCentrosSena/(?P<pk>\d+)/',editarCentrosSena, name='editarCentrosSena'),
    url(r'^eliminarCentrosSena/(?P<pk>\d+)/',eliminarCentrosSena, name='eliminarCentrosSena'),
    url(r'^editarSedeUni/(?P<pk>\d+)/',editarSedeUni, name='editarSedeUni'),
    url(r'^eliminarSedeUni/(?P<pk>\d+)/',eliminarSedeUni, name='eliminarSedeUni'),
    url(r'^colegios',colegios, name='colegios'),
    url(r'^centrosSena',centrosSena, name='centrosSena'),
    url(r'^reporte',reporte, name='reporte'),
    url(r'^InformeVarios',InformeVarios, name='InformeVarios'),
    url(r'^salidaPdf',salidaPdf, name='salidaPdf'),#GEt
    url(r'^informeVca/$', informeVca, name='informeVca'),
    url(r'^informeAlumnos/$', informeAlumnos, name='informeAlumnos'),
    url(r'^excelAgendados',excelAgendados, name='excelAgendados'),
    url(r'^sedes',sedes, name='sedes'),
    #url(r'^Veredas',Veredas, name='Veredas'),
    url(r'^informe',informe, name='informe'),
    url(r'^estimulos',estimulos, name='estimulos'),
    url(r'^validaDocumento',validaDocumento, name='validaDocumento'),
    url(r'^fechaEntrevista',fechaEntrevista, name='fechaEntrevista'),
    url(r'^horaEntrevista',horaEntrevista, name='horaEntrevista'),
    url(r'^listaEntrevista',listaEntrevista, name='listaEntrevista'),
    url(r'^editaBusqAgenda',editaBusqAgenda, name='editaBusqAgenda'),
    url(r'^editarFormularioUsuario',editarFormularioUsuario, name='editarFormularioUsuarioF'),
    url(r'^editaFechaEntrevista',editaFechaEntrevista, name='editaFechaEntrevista'),
    url(r'^editarBusquedaParcialmente/(?P<pk>\d+)/',editarBusquedaParcialmente, name='editarBusquedaParcialmente'),
    url(r'^esti_form/$',esti_form, name='esti_form'),
    #url(r'^configuracion$',configuracion, name='configuracion'),
    url(r'^pdf',salidaPdf, name='pdf'),
    url(r'^passwordResetForm',passwordResetForm, name='passwordResetForm'),
    url(r'^admin/', admin.site.urls),

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),


    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
]

proyecto/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
lst_sexo = ("M","masculino"),("F","femenino")
lst_estado = ("S","si"),("N","no")

class Inst_educativas(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=30)

class Inst_educativas2(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=30)

class SedeInstitucion(models.Model):
    sede = models.CharField(max_length=50)
    institucion = models.ForeignKey(Inst_educativas, null=True)

class SedeInstitucion2(models.Model):
    sede = models.CharField(max_length=50)
    institucion = models.ForeignKey(Inst_educativas2, null=True)

class Grado(models.Model):
    grado = models.CharField(max_length=15)

class Grupos(models.Model):
    grupo = models.CharField(max_length=20)
    grado = models.ForeignKey(Grado, null=True)

class Grupos2(models.Model):
    grupo = models.CharField(max_length=20)
    grado = models.ForeignKey(Grado, null=True)
    #class Meta:
    #    verbose_name = 'Institucion_educativa'
    #    verbose_name_plural = 'Inst_educativas'


    def def__Unicode__(self):
        return self.nombre

class Usuario(User):
    class Meta:
        proxy = True

class Municipios(models.Model):
    municipio = models.CharField(max_length=50)

class Veredas(models.Model):
    vereda = models.CharField(max_length=50)

class Colegios(models.Model):
    colegio = models.CharField(max_length=150)

class CentrosSena(models.Model):
    centroSena = models.CharField(max_length=150)

class Sedes(models.Model):
    sede = models.CharField(max_length=150)

class Universidades(models.Model):
    universidad = models.CharField(max_length=150)

class Sisben(models.Model)  :
    puntaje = models.CharField(max_length=15)

class Estrato(models.Model)  :
    estrato = models.CharField(max_length=15)

class Genero(models.Model)  :
    estrato = models.CharField(max_length=15)

class FormularioEstimulos(models.Model)  :

    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    tipoDocumento = models.CharField(max_length=10)
    documentoOtro = models.CharField(max_length=30)
    documento = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    celular = models.CharField(max_length=50)
    genero = models.CharField(max_length=30)
    edad = models.CharField(max_length=30)
    estadoCivil = models.CharField(max_length=30)
    cabezaFamilia = models.CharField(max_length=30)
    hijos = models.CharField(max_length=10)
    pertenencia = models.CharField(max_length=30)
    pertenenciaOtro = models.CharField(max_length=50)
    direccionEstudiante = models.CharField(max_length=100)
    ciudadEstudiante = models.CharField(max_length=150)
    barrioEstudiante = models.CharField(max_length=150)
    ubicacionEstudiante = models.CharField(max_length=30)
    vivienda = models.CharField(max_length=30)
    estrato = models.CharField(max_length=30)
    sisben = models.CharField(max_length=30)
    nucleoFamiliar = models.CharField(max_length=30)
    direccionPadres = models.CharField(max_length=100)
    ciudadPadres = models.CharField(max_length=150)
    barrioPadres = models.CharField(max_length=150)
    ubicacionPadres = models.CharField(max_length=30)
    serviciosPublicos = models.CharField(max_length=70)
    dependenciaEconomica = models.CharField(max_length=30)
    dependenciaOtro = models.CharField(max_length=50)
    ingresosFamilia = models.CharField(max_length=30)
    colegio = models.CharField(max_length=150)
    oficialPrivado = models.CharField(max_length=30)
    anoTerminacion = models.CharField(max_length=30)
    actaGrado = models.CharField(max_length=50)
    universidad = models.CharField(max_length=150)
    centrosSena = models.CharField(max_length=150)
    sede = models.CharField(max_length=50)
    acreditacionUniversidad = models.CharField(max_length=30)
    carrera = models.CharField(max_length=100)
    tecnicaTecnologica = models.CharField(max_length=30)
    acreditacionCarrera = models.CharField(max_length=30)
    cicloEducacion = models.CharField(max_length=30)
    semestreEnCurso = models.CharField(max_length=30)
    modalidad = models.CharField(max_length=30)
    modalidadOtro = models.CharField(max_length=50)
    propedeutico = models.CharField(max_length=30)
    propedeuticoOtro = models.CharField(max_length=50)
    valorMatricula = models.CharField(max_length=30)
    beneficiarioprogramas = models.CharField(max_length=30)
    programaOtro = models.CharField(max_length=50)
    incentivoEducativo = models.CharField(max_length=30)
    cuantasVeces = models.CharField(max_length=30)
    extraAcademicas = models.CharField(max_length=30)
    extraAcademicaPaga = models.CharField(max_length=30)
    parentesco1 = models.CharField(max_length=100)
    parentesco2 = models.CharField(max_length=100)
    parentesco3 = models.CharField(max_length=100)
    parentesco4 = models.CharField(max_length=100)
    parentesco5 = models.CharField(max_length=100)
    parentesco6 = models.CharField(max_length=100)
    parentesco7 = models.CharField(max_length=100)
    totalObtenido = models.CharField(max_length=100)

class Persona(models.Model):
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    documento = models.CharField(max_length=12)
    email = models.EmailField(max_length=30)
    sexo = models.CharField(max_length=1, choices= lst_sexo)

class Estudiante(models.Model):
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    documento = models.CharField(max_length=12)
    carrera = models.CharField(max_length=50)
    genero = models.CharField(max_length=1, choices= lst_sexo)
    sisben = models.CharField(max_length=12)
    estrato = models.ForeignKey('Estrato',models.DO_NOTHING)
    direccion = models.CharField(max_length=60)
    contacto = models.CharField(max_length=12)
    nacimiento = models.CharField(max_length=12)
    email = models.EmailField(max_length=30)

class Alumno(models.Model):
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    documento = models.CharField(max_length=12)
    grado = models.ForeignKey('Grado',models.DO_NOTHING)
    genero = models.CharField(max_length=1, choices= lst_sexo)
    sisben = models.CharField(max_length=12)
    estrato = models.ForeignKey('Estrato',models.DO_NOTHING)
    transporte = models.CharField(max_length=1, choices= lst_estado)
    direccion = models.CharField(max_length=60)
    familias = models.CharField(max_length=1, choices= lst_estado)
    alimentacion = models.CharField(max_length=1, choices= lst_estado)
    desplazado = models.CharField(max_length=1, choices= lst_estado)
    contacto = models.CharField(max_length=12)
    nacimiento = models.CharField(max_length=12)
    email = models.EmailField(max_length=30)
    credo = models.CharField(max_length=25)

class Alumno2(models.Model):
    procedencia = models.ForeignKey('Veredas', null=True)
    institucion = models.ForeignKey('Inst_educativas2',null=True)
    sede = models.ForeignKey('SedeInstitucion2',null=True)
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    documento = models.CharField(max_length=20)
    grado = models.ForeignKey('Grado',models.DO_NOTHING)
    genero = models.CharField(max_length=20, choices= lst_sexo)
    transporte = models.CharField(max_length=20, choices= lst_estado)
    direccion = models.CharField(max_length=60)
    familias = models.CharField(max_length=20, choices= lst_estado)
    alimentacion = models.CharField(max_length=20, choices= lst_estado)
    desplazado = models.CharField(max_length=20, choices= lst_estado)
    contacto = models.CharField(max_length=20)
    nacimiento = models.CharField(max_length=20)
    email = models.EmailField(max_length=30)
    credo = models.CharField(max_length=25)

class docente(models.Model):
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    documento = models.CharField(max_length=12)
    email = models.EmailField(max_length=30)
    asignatura = models.CharField(max_length=50)
    contacto = models.CharField(max_length=12)

class Horas(models.Model):
    hora = models.CharField(max_length=15)

class Video(models.Model):
    video = models.CharField(max_length=500)

class Fechas(models.Model):
    hora =  models.ForeignKey(Horas, null=True)
    fecha = models.CharField(max_length=15, null=True)
    nombre = models.ForeignKey(FormularioEstimulos, null=True)

class Traza(models.Model):
    usuario = models.IntegerField()
    tipo= models.CharField(max_length=1)
    tiempo= models.DateTimeField(default=datetime.datetime.now)
    accion= models.TextField()

templates/actualiza_docentes.html
{% extends 'plantilla.html' %}
{% block title%} EDUCACION {%endblock %}



{%  block content %}


{% endblock %}

templates/busquedas2.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock %}</title>

    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>educacion</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/overrides.css" rel="stylesheet">
    <link href="/static/css/procss.css" rel="stylesheet">
    <script src="/static/js/html5shiv.min.js"></script>
    <script src="/static/js/respond.min.js"></script>

</head>
<body>



<!-- Static navbar -->
<nav class="navbar navbar-default ">
    <div class="col-sm-12">
        <div class="row">


            <div class="container-fluid barras">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">  Navegación de palanca</font> </span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   <!-- <img src="/static/img/escudo-anapoima.png">-->

                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Modificar<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="docentes.html">docentes</a></li>
                                <li><a href="matriculas.html">  estudiantes  </a></li>
                                <li><a href="matriculas.html">  traslado  </a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tramites <span class="caret"></span></a>
                            <ul class="dropdown-menu color">
                                <li><a href="matriculas.html">  matriculas  </a></li>
                                <li><a href="docentes.html">  docentes  </a></li>
                                <li><a href="registro.html">Usuarios</a></li>

                            </ul>
                        </li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                             <form class="navbar-form navbar-right" action="{% url 'busquedas_alumnos' %}" method="get" >
                                 <form class="navbar-form navbar-right">
                                    <input type="text" name="dato" class="form-control" id="txtBuscar" placeholder="Buscar por ...">
                                    <button id="btnBuscar" name="captar" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </form>
                            </form>
                        </li>
                         <li>
                            <a href="/logout.html" >
                                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> cerrar cesion
                            </a>
                        </li>
                    </ul>

                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </div>
    </div>

</nav>

<div class="container initial">

    <div class="col-sm-12 form-group">
        <div class="col-sm-1">

         </div>
        <div class= "cuerpo">
            <img src="/static/img/vamos.png" width="100%" style="margin: 0%; padding: 0%">
         </div>

    </div>

    <!-- Main component for a primary marketing message or call to action -->
    <div class="row">
            <form class="navbar-form" action="{% url 'busquedas_alumnos' %}" method="get" >
                <div class="col-sm-12">
                    <legend>BUSQUEDAS SELECTIVAS ALUMNO</legend>
                </div>
                <p>  secretaria de educacion de anapoima aqui podras hacer busquedas por diferentes criterios nombre, apellido o documento digita en buscar tu seleccion .  </p>

            </form>
    </div>
</div>


        <br>
        <div class="navbar navbar-default navbar-fixed-bottom">
            <div class="container">
                <p class="navbar-text">© 2016 Tecnología en Desarrollo de sistemas de información</p>
            </div><!--container-->
        </div><!--navbar-->


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="static/javascript/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="static/vendors/bootstrap-3.3.6/dist/js/bootstrap.min.js"></script>
        <script src="static/vendors/bootstrap-3.3.6/dist/js/bootstrap.min.js"></script>


    </div>

</div> <!-- /container -->

<div class="navbar navbar-default navbar-fixed-bottom barras">
    <div class="container">
        <p class="navbar-text ">© 2016 secretaria de educacion de anapoima </p>

    </div><!--container-->
</div><!--navbar-->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../static/vendors/bootstrap-3.3.6/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script><div id="goog-gt-tt" class="goog-tooltip skiptranslate" dir="ltr" style="visibility: hidden; left: 164px; top: 62px; display: none;"><div style="padding: 8px;"><div><div class="logo"><img src="https://www.gstatic.com/images/branding/product/1x/translate_24dp.png" width="20" height="20"></div></div></div><div class="top" style="padding: 8px; float: left; width: 100%;"><h1 class="title gray">Texto original</h1></div><div class="middle" style="padding: 8px;"><div class="original-text">About</div></div><div class="bottom" style="padding: 8px;"><div class="activity-links"><span class="activity-link">Sugiere una traducción mejor</span><span class="activity-link"></span></div><div class="started-activity-container"><hr style="color: #CCC; background-color: #CCC; height: 1px; border: none;"><div class="activity-root"></div></div></div><div class="status-message" style="display: none; opacity: 0;"></div></div>


</body>
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


</html>

templates/configuraMatriculas.html
{% extends 'plantilla.html' %}
{% block title%} EDUCACION {%endblock %}

{%  block content %}
 <div class="panel panel-headline">
      <div class="panel-heading">
        <h2 class="panel-title"><b>Configuración</b></h2>
        <p class="panel-subtitle"><b>Panel Administrativo - Configuración</b></p>
      </div>

</div>

<div class="panel">
    <div class="panel-body">
          <div class="table-responsive">


          <div class="row">

                <div class="col-md-6">
                <a href="configuraInstitucion"><i class="fa fa-university"></i>Institucion Educativa</a>
                <hr />
                </div>

                <div class="col-md-6">
                 <a href="configuraSede"><i class="fa fa-object-group"></i>Sedes</a>
                 <hr />
                </div>

                <div class="col-md-6">
                 <a href="configuraGrado"> <i class="fa fa-graduation-cap"></i>Grados</a>
                 <hr />
                </div>

                <div class="col-md-6">
                 <a href="configuraGrupo"><i  class="fa fa-users"></i> Grupos </a>
                 <hr />
                </div>

          </div>

          </div>
    </div>
</div>

</div>

{% endblock %}

templates/formulario_exitoso.html
{% extends 'plantilla-index.html' %}
{% load staticfiles %}

{%  block content %}

<br><br><br>

    <div class="container">
    	<div class="row">

    		  <div class="col-md-12">
    		  	<div class="row">
    		  		<div class="content-box-large">
    		  				<div class="panel-heading">
                  <!--  <form class="" action="{% url 'fechaEntrevista' %}" method="POST">-->
                    <form class="" action="{% url 'horaEntrevista' %}" method="POST">
                        {% csrf_token %}
                    <div class="col-sm-1">

                    </div>
                    <div class="col-sm-11 form-group">
                      {% if documento %}
                            <!--<input type="hidden" name="doc" id="documento" value="{{ documento }}">
                              <label class="control-label" for="textinput">Programe dia y hora para su entrevista</label><br>
                              <input class="form-control" type="date" onchange="this.form.submit()" id="dia" name="dia" step="1" min="2018-09-20" max="2018-09-22" value="{{ fecha }}">
                            -->

                              <input type="hidden" name="doc" id="documento" value="{{ documento }}">
                              <input type="hidden" name="dia" id="dia" value="2018-09-20">
                              <input type="hidden" name="diaMes" id="diaMes" value="2018-09-20">
                              <input type="hidden" name="docum" id="docum" value="{{ documento }}">
                              <input type="hidden" name="hora" id="id_hora" value="22">
                              <p>&nbsp; &nbsp; </p>
                              <button class="btn btn-primary" type="submit">Guardar</button>
                              <p>&nbsp; &nbsp; </p>
                      {% endif %}
                      </form>
                      {% if lista_nueva %}
                      <form class="" action="{% url 'horaEntrevista' %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="diaMes" id="diaMes" value="{{ fecha }}">
                          <input type="hidden" name="docum" id="docum" value="{{ documento }}">
                          <label class="control-label" for="textinput">Hora de la entrevista</label><br>
                          <select id="id_hora" name="hora" type="text" class="form-control input-md" required>
                              <option value="{{ hora }}">Hora</option>
                                  {% for row in lista_nueva %}
                                      <option value="{{ row.id }}">{{ row.hora }}</option>
                                  {% endfor %}
                          </select>
                          <p>&nbsp; &nbsp; </p>
                          <button class="btn btn-primary" type="submit">Guardar</button>
                          <p>&nbsp; &nbsp; </p>

                    </div>
                    </form>
                    {% endif %}
                    {% if nombreGuardado %}
                    <form class="" action="{% url 'reporte' %}" method="POST">
                        {% csrf_token %}
                      <div class="">
                        <input type="hidden" name="doc" id="documento" value="{{ documen }}">
                        <!--<h4>{{ nombreGuardado }} Se agendó su entrevista  para el día {{ diaGuardado }} a las {{ horaGuardada }}</h4>-->
                        <h4>{{ nombreGuardado }} A guardado satisfactoriamente su informacion</h4>
                        <label for="">Descarge el pdf de su registro</label>  <button class="btn btn-primary" type="submit">pdf</button>
                      </div>
                    </form>
                    {% endif %}

                    {% if nombreAgendado %}
                    <form class="" action="{% url 'reporte' %}" method="POST">
                        {% csrf_token %}
                      <div class="">
                        <input type="hidden" name="doc" id="documento" value="{{ documen }}">
                        <h4>{{ nombreAgendado }} Ya se encuentra registrado(a) y agendado(a)</h4>
                        <label for="">Descarge el pdf de su registro</label>  <button class="btn btn-primary" type="submit">pdf</button>
                      </div>
                    </form>
                    {% endif %}
    	            </div>
    	       </div>
    	     </div>
         </div>

		  </div>
		</div>
  </div></div></div></div></div></div>

<br><br><br>
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
{% endblock %}